import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 bg-gray-900 text-white shadow-lg rounded-lg mt-10">
      <h1 className="text-3xl font-bold text-center mb-6 text-blue-400">Terms and Conditions</h1>
      <p className="text-gray-300 leading-relaxed">
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder. 
        This electronic record is generated by a computer system and does not require physical or digital signatures.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Platform Ownership</h2>
      <p className="text-gray-300">
        The Platform is owned by HackEx, a company incorporated under the Companies Act, 1956, with its registered office at 
        1-8-151/1, Road No-4, Ganeshpuri Colony, Dilshukhnagar, Hyderabad-500060.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">User Agreement</h2>
      <p className="text-gray-300">
        By accessing or using the Platform, you agree to abide by these Terms and Conditions. If you transact on the Platform, you
        shall be subject to the applicable policies.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Use of Services</h2>
      <p className="text-gray-300">
        You agree to provide accurate and complete information when registering or using our Platform. You acknowledge that
        the contents of the Platform, including design and layout, are proprietary to HackEx.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Restrictions and Liability</h2>
      <p className="text-gray-300">
        Unauthorized use of the Platform may result in legal action. The Platform Owner is not liable for inaccuracies, business
        interruptions, or indirect damages caused by the use of our Services.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Indemnity</h2>
      <p className="text-gray-300">
        You agree to indemnify and hold HackEx and its affiliates harmless from any claims, penalties, or legal actions arising
        from your use of the Platform, violation of Terms, or infringement of third-party rights.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Dispute Resolution</h2>
      <p className="text-gray-300">
        These Terms shall be governed by Indian law. Any disputes shall be subject to the exclusive jurisdiction of the courts in
        Hyderabad, India.
      </p>
      
      <h2 className="text-2xl font-semibold text-blue-300 mt-6">Changes to Terms</h2>
      <p className="text-gray-300">
        We may update these Terms at any time. Users are responsible for reviewing them periodically.
      </p>
      
      <p className="text-gray-400 mt-6 text-sm text-center">Last updated: February 1, 2025</p>
    </div>
  );
};

export default TermsAndConditions;
